services:
  backend:
    build:
      context: ./backend
      args:
        VERSION: ${VERSION:-dev}
    ports:
      - "8080:8080"
    environment:
      CALC_MIN: ${CALC_MIN}
      CALC_MAX: ${CALC_MAX}

  frontend:
    build:
      context: ./frontend
      args:
        VITE_CALC_MIN: ${VITE_CALC_MIN:-}
        VITE_CALC_MAX: ${VITE_CALC_MAX:-}
    ports:
      - "80:80"
    depends_on:
      - backend
